# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az extension add -n ml -y

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      az login --service-principal -u "40861cb6-cefc-4904-a8ab-528434625238" -p "~tx8Q~0iEpHzrEMD64V1TuP1Qg7eE.H5vm_LebYU" --tenant "16b3c013-d300-468d-ac64-7eda0820b6d3"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az --version
      # az account show