# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: runid
  value: ""

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az extension add -n ml -y

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az login --service-principal -u $(clientid) -p $(secret) --tenant $(tenantid)

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az --version
      # az account show

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd src
      run_id=$(az ml job create --file job.yml --resource-group "rg-dev-mlops" --workspace-name "mlw-dev-mlops" --query name -o tsv)
      echo "##vso[task.setvariable variable=runid;]$run_id"
      echo "Run ID from above Job Run is $run_id stored in environment variable"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "Run ID from above Job Run is $run_id stored in environment variable"'

- task: bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd src
      az ml model create -n diabetes-data-example -p runs:/trainrun1/model --type mlflow_model --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops

- task: bash@3
  inputs:
    targetType: 'inline'
    script: |
        cd src
        az ml online-endpoint delete --name diabetesendpointbb22 --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops --yes

- task: bash@3
  inputs:
    targetType: 'inline'
    script: |
        cd src
        az ml online-endpoint create --name diabetesendpointbb22 -f endpoint.yml --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops

- task: bash@3
  inputs:
    targetType: 'inline'
    script: |
        cd src
        az ml online-deployment create --name blue --endpoint diabetesendpointbb22 --file blue-deployment.yml --all-traffic --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops

- task: bash@3
  inputs:
    targetType: 'inline'
    script: |
        cd src
        az ml online-endpoint show -n diabetesendpointbb22 --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops

- task: bash@3
  inputs:
    targetType: 'inline'
    script: |
        cd src
        az ml online-endpoint invoke --name diabetesendpointbb22 --request-file sample-request.json --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops