# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: runid
  value: ""

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az extension add -n ml -y

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here      
      az login --service-principal -u $(clientid) -p $(secret) --tenant $(tenantid)

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      az --version
      # az account show

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd src
      run_id=$(az ml job create --file job.yml --resource-group "rg-dev-mlops" --workspace-name "mlw-dev-mlops" --query name -o tsv)
      echo "##vso[task.setvariable variable=runid;]$run_id"
      echo "Run ID from above Job Run is $run_id stored in environment variable"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo "Run ID from above Job Run is ${{ variables.runid}} stored in environment variable"'