$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: diabetesendpoint
model: azureml:diabetes-data-example@latest
instance_type: Standard_FSs_v2
instance_count: 1