name: Run AML job

on:
  label:
    types:
      - created
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops' 
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit training job
      id: diabetes-mlops-challenge
      run: |
        cd src
        az ml job create --file job.yml --resource-group "${{ github.event.inputs.resource_group }}" --workspace-name "${{ github.event.inputs.aml_workspace }}"