name: Trigger GitHub Actions with trunk-based development

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Azure ML workspace as default
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}"
        az configure --defaults workspace="${{ github.event.inputs.aml_workspace }}"

    - name: Submit Training Job
      run: |
            az ml job create --file src/job.yml --resource-group "${{ github.event.inputs.resource_group }}" --workspace-name "${{ github.event.inputs.aml_workspace }}"