name: Deploy to Development and Production

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops' 
        type: string

env:
  run_id: ""

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit Training Job
      run: |
        cd src
        run_id=$(az ml job create --file job.yml --resource-group "rg-dev-mlops" --workspace-name "mlw-dev-mlops" --query name -o tsv)
        echo "run_id=$run_id" >> $GITHUB_ENV
        az ml job show --name $run_id --resource-group "rg-dev-mlops" --workspace-name "mlw-dev-mlops"
    - name: Display Run_details
      run: |
        cd src
        az ml job show --name $run_id --resource-group "rg-dev-mlops" --workspace-name "mlw-dev-mlops"
  deployment:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set Defaults for Azure Sub
      run: |
        az account set --subscription 80ef7369-572a-4abd-b09a-033367f44858
        az configure --defaults workspace=mlw-dev-mlops group=rg-dev-mlops
    - name: Register Model
      run: |
        cd src
        az ml model create -n diabetes-data-example -p runs:/trainrun1/model --type mlflow_model --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
    - name: Delete Online Endpoint
      continue-on-error: true
      run: |
        cd src
        az ml online-endpoint delete --name diabetesendpointbb22 --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops --yes
    - name: Create Online Endpoint
      run: |
        cd src
        az ml online-endpoint create --name diabetesendpointbb22 -f endpoint.yml --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
    - name: Update Deployment for above model
      run: |
        cd src
        az ml online-deployment create --name blue --endpoint diabetesendpointbb22 --file blue-deployment.yml --all-traffic --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
    - name: Show the endpoint
      run: |
        cd src
        az ml online-endpoint show -n diabetesendpointbb22 --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
    - name: Invoke the endpoint
      run: |
        cd src
        az ml online-endpoint invoke --name diabetesendpointbb22 --request-file sample-request.json --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops
